"""Add table gold_kpis

Revision ID: 1c3b6a8766ee
Revises: 63a2129d384b
Create Date: 2026-09-09 10:40:58.769076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c3b6a8766ee'
down_revision: Union[str, Sequence[str], None] = '63a2129d384b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
    'gold_kpis',

    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('id_kpi', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=True),
    sa.Column('id_client', sa.Integer(), nullable=False),

    sa.ForeignKeyConstraint(['id_client'], ['clients.id']),
    sa.ForeignKeyConstraint(['id_kpi'], ['kpis.id']),

    sa.PrimaryKeyConstraint('id'),

    sa.UniqueConstraint(
        'month',
        'year',
        'id_kpi',
        'id_client'
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gold_kpis')
    # ### end Alembic commands ###
