"""Create new table  kpis

Revision ID: 248e7140f48a
Revises: a66fd70b0a6c
Create Date: 2026-08-26 12:26:20.730250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '248e7140f48a'
down_revision: Union[str, Sequence[str], None] = 'a66fd70b0a6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gold_campaign_insights',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('year', sa.String(), nullable=False),
    sa.Column('adset_name', sa.String(), nullable=True),
    sa.Column('impressions', sa.Numeric(), nullable=True),
    sa.Column('clicks', sa.Numeric(), nullable=True),
    sa.Column('spend', sa.Float(), nullable=True),
    sa.Column('cpm', sa.Float(), nullable=True),
    sa.Column('cpc', sa.Float(), nullable=True),
    sa.Column('cpp', sa.Float(), nullable=True),
    sa.Column('videos_view', sa.Numeric(), nullable=True),
    sa.Column('message_connection', sa.Numeric(), nullable=True),
    sa.Column('purchase', sa.Numeric(), nullable=True),
    sa.Column('cost_per_message', sa.Float(), nullable=True),
    sa.Column('cost_per_sale', sa.Float(), nullable=True),
    sa.Column('campaign_id', sa.String(), nullable=True),
    sa.Column('ad_accounts_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ad_accounts_id'], ['ad_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'month', 'year', 'adset_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gold_campaign_insights')
    op.drop_table('kpis')
    # ### end Alembic commands ###
