"""Create Process log and change pipeline run 

Revision ID: 527e4566e0c0
Revises: 5dbe92518f11
Create Date: 2026-08-11 11:23:47.476423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '527e4566e0c0'
down_revision: Union[str, Sequence[str], None] = '5dbe92518f11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('pipeline_run_id', sa.BigInteger(), nullable=True),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('process_name', sa.String(), nullable=True),
    sa.Column('layer', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('finished_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('records_read', sa.Integer(), nullable=True),
    sa.Column('records_created', sa.Integer(), nullable=True),
    sa.Column('records_updated', sa.Integer(), nullable=True),
    sa.Column('records_failed', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('cretated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_run.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pipeline_run_id', 'process_name')
    )
    op.create_unique_constraint(None, 'pipeline_run', ['excecution_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pipeline_run', type_='unique')
    op.drop_table('process_log')
    # ### end Alembic commands ###
