"""Add column code to kpis

Revision ID: 5de345ec1ac2
Revises: c61a63318b2f
Create Date: 2026-09-09 09:48:59.689105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5de345ec1ac2'
down_revision: Union[str, Sequence[str], None] = 'c61a63318b2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpis', sa.Column('code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kpis', 'code')
    # ### end Alembic commands ###
