"""Add colum leads in siver layer

Revision ID: 63a2129d384b
Revises: 5de345ec1ac2
Create Date: 2026-09-09 10:26:48.834273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63a2129d384b'
down_revision: Union[str, Sequence[str], None] = '5de345ec1ac2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('silver_campaign_insights', sa.Column('leads', sa.Numeric(), nullable=True))
    op.drop_column('silver_campaign_insights', 'cost_per_sale')
    op.drop_column('silver_campaign_insights', 'cost_per_message')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('silver_campaign_insights', sa.Column('cost_per_message', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('silver_campaign_insights', sa.Column('cost_per_sale', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('silver_campaign_insights', 'leads')
    # ### end Alembic commands ###
