"""Add account_id to broze layer

Revision ID: 73bde436b9e9
Revises: 78bf459088d7
Create Date: 2026-08-10 18:12:06.535863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73bde436b9e9'
down_revision: Union[str, Sequence[str], None] = '78bf459088d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bronze_campaign_insights', sa.Column('campaign_id', sa.String(), nullable=True))
    op.add_column('bronze_campaign_insights', sa.Column('ad_accounts_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('bronze_campaign_insights_campaing_id_date_start_adset_name__key'), 'bronze_campaign_insights', type_='unique')
    op.create_unique_constraint(None, 'bronze_campaign_insights', ['campaign_id', 'date_start', 'adset_name', 'ad_name'])
    op.create_foreign_key(None, 'bronze_campaign_insights', 'ad_accounts', ['ad_accounts_id'], ['id'])
    op.drop_column('bronze_campaign_insights', 'campaing_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bronze_campaign_insights', sa.Column('campaing_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bronze_campaign_insights', type_='foreignkey')
    op.drop_constraint(None, 'bronze_campaign_insights', type_='unique')
    op.create_unique_constraint(op.f('bronze_campaign_insights_campaing_id_date_start_adset_name__key'), 'bronze_campaign_insights', ['campaing_id', 'date_start', 'adset_name', 'ad_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('bronze_campaign_insights', 'ad_accounts_id')
    op.drop_column('bronze_campaign_insights', 'campaign_id')
    # ### end Alembic commands ###
