"""initial

Revision ID: 78bf459088d7
Revises: 
Create Date: 2026-08-10 17:51:47.049893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78bf459088d7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bronze_campaign_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_start', sa.Date(), nullable=True),
    sa.Column('adset_name', sa.String(), nullable=True),
    sa.Column('ad_name', sa.String(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=True),
    sa.Column('is_processed', sa.Integer(), nullable=True),
    sa.Column('campaing_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaing_id', 'date_start', 'adset_name', 'ad_name')
    )
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gold_campaign_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('year', sa.String(), nullable=False),
    sa.Column('adset_name', sa.String(), nullable=True),
    sa.Column('impressions', sa.Numeric(), nullable=True),
    sa.Column('clicks', sa.Numeric(), nullable=True),
    sa.Column('spend', sa.Float(), nullable=True),
    sa.Column('cpm', sa.Float(), nullable=True),
    sa.Column('cpc', sa.Float(), nullable=True),
    sa.Column('cpp', sa.Float(), nullable=True),
    sa.Column('videos_view', sa.Numeric(), nullable=True),
    sa.Column('message_connection', sa.Numeric(), nullable=True),
    sa.Column('purchase', sa.Numeric(), nullable=True),
    sa.Column('cost_per_message', sa.Float(), nullable=True),
    sa.Column('cost_per_sale', sa.Float(), nullable=True),
    sa.Column('campaing_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaing_id', 'month', 'year', 'adset_name')
    )
    op.create_table('silver_campaign_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_name', sa.String(), nullable=True),
    sa.Column('adset_name', sa.String(), nullable=True),
    sa.Column('ad_name', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('impressions', sa.Numeric(), nullable=True),
    sa.Column('clicks', sa.Numeric(), nullable=True),
    sa.Column('spend', sa.Float(), nullable=True),
    sa.Column('cpm', sa.Float(), nullable=True),
    sa.Column('cpc', sa.Float(), nullable=True),
    sa.Column('cpp', sa.Float(), nullable=True),
    sa.Column('videos_view', sa.Numeric(), nullable=True),
    sa.Column('message_connection', sa.Numeric(), nullable=True),
    sa.Column('purchase', sa.Numeric(), nullable=True),
    sa.Column('cost_per_message', sa.Float(), nullable=True),
    sa.Column('cost_per_sale', sa.Float(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=True),
    sa.Column('is_processed', sa.Integer(), nullable=True),
    sa.Column('campaing_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaing_id', 'date', 'adset_name', 'ad_name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('rol', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ad_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_table('users_clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ad_campaings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=True),
    sa.Column('campaign_name', sa.String(), nullable=True),
    sa.Column('objective', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('ad_accounts_id', sa.Integer(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ad_accounts_id'], ['ad_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'ad_accounts_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ad_campaings')
    op.drop_table('users_clients')
    op.drop_table('ad_accounts')
    op.drop_table('users')
    op.drop_table('silver_campaign_insights')
    op.drop_table('gold_campaign_insights')
    op.drop_table('clients')
    op.drop_table('bronze_campaign_insights')
    # ### end Alembic commands ###
