"""Quitar id  de kpis_clients y hacerlo compuesta por lod foreign keys

Revision ID: 820a2981f6ea
Revises: b61581f4f2ed
Create Date: 2026-08-27 16:32:02.705588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '820a2981f6ea'
down_revision: Union[str, Sequence[str], None] = 'b61581f4f2ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gold_campaign_insights')
    op.alter_column('kpis_clients', 'id_client',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('kpis_clients', 'id_kpi',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('kpis_clients', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpis_clients', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('kpis_clients', 'id_kpi',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('kpis_clients', 'id_client',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('gold_campaign_insights',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('month', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('year', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('adset_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('impressions', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('clicks', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('spend', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cpm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cpc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cpp', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('videos_view', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('message_connection', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('purchase', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('cost_per_message', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cost_per_sale', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('campaign_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ad_accounts_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ad_accounts_id'], ['ad_accounts.id'], name=op.f('gold_campaign_insights_ad_accounts_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('gold_campaign_insights_pkey')),
    sa.UniqueConstraint('campaign_id', 'month', 'year', 'adset_name', name=op.f('gold_campaign_insights_campaign_id_month_year_adset_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
