"""Add autoincrement id gold_kpis

Revision ID: 8b0696531d84
Revises: 1c3b6a8766ee
Create Date: 2026-09-09 10:52:44.641672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b0696531d84'
down_revision: Union[str, Sequence[str], None] = '1c3b6a8766ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
