"""Add new gold table

Revision ID: c7641a2625b6
Revises: 820a2981f6ea
Create Date: 2026-09-02 13:41:05.846435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7641a2625b6'
down_revision: Union[str, Sequence[str], None] = '820a2981f6ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gold_campaign_insights',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('ad_name', sa.String(), nullable=False),
    sa.Column('adset_name', sa.String(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('spend', sa.Numeric(), nullable=True),
    sa.Column('cpm', sa.Numeric(), nullable=True),
    sa.Column('cpc', sa.Numeric(), nullable=True),
    sa.Column('cpp', sa.Numeric(), nullable=True),
    sa.Column('videos_view', sa.Integer(), nullable=True),
    sa.Column('message_connection', sa.Integer(), nullable=True),
    sa.Column('purchase', sa.Integer(), nullable=True),
    sa.Column('lead', sa.Numeric(), nullable=True),
    sa.Column('cost_per_message', sa.Numeric(), nullable=True),
    sa.Column('cost_per_purchase', sa.Numeric(), nullable=True),
    sa.Column('cost_per_lead', sa.Numeric(), nullable=True),
    sa.Column('ad_accounts_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ad_accounts_id'], ['ad_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'year', 'month', 'ad_name', 'adset_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gold_campaign_insights')
    # ### end Alembic commands ###
