"""Add account_id to silver and gold layer

Revision ID: e600ae06d433
Revises: 73bde436b9e9
Create Date: 2026-08-10 18:15:50.586505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e600ae06d433'
down_revision: Union[str, Sequence[str], None] = '73bde436b9e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gold_campaign_insights', sa.Column('campaign_id', sa.String(), nullable=True))
    op.add_column('gold_campaign_insights', sa.Column('ad_accounts_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('gold_campaign_insights_campaing_id_month_year_adset_name_key'), 'gold_campaign_insights', type_='unique')
    op.create_unique_constraint(None, 'gold_campaign_insights', ['campaign_id', 'month', 'year', 'adset_name'])
    op.create_foreign_key(None, 'gold_campaign_insights', 'ad_accounts', ['ad_accounts_id'], ['id'])
    op.drop_column('gold_campaign_insights', 'campaing_id')
    op.add_column('silver_campaign_insights', sa.Column('campaign_id', sa.String(), nullable=True))
    op.add_column('silver_campaign_insights', sa.Column('ad_accounts_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('silver_campaign_insights_campaing_id_date_adset_name_ad_nam_key'), 'silver_campaign_insights', type_='unique')
    op.create_unique_constraint(None, 'silver_campaign_insights', ['campaign_id', 'date', 'adset_name', 'ad_name'])
    op.create_foreign_key(None, 'silver_campaign_insights', 'ad_accounts', ['ad_accounts_id'], ['id'])
    op.drop_column('silver_campaign_insights', 'campaing_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('silver_campaign_insights', sa.Column('campaing_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'silver_campaign_insights', type_='foreignkey')
    op.drop_constraint(None, 'silver_campaign_insights', type_='unique')
    op.create_unique_constraint(op.f('silver_campaign_insights_campaing_id_date_adset_name_ad_nam_key'), 'silver_campaign_insights', ['campaing_id', 'date', 'adset_name', 'ad_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('silver_campaign_insights', 'ad_accounts_id')
    op.drop_column('silver_campaign_insights', 'campaign_id')
    op.add_column('gold_campaign_insights', sa.Column('campaing_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'gold_campaign_insights', type_='foreignkey')
    op.drop_constraint(None, 'gold_campaign_insights', type_='unique')
    op.create_unique_constraint(op.f('gold_campaign_insights_campaing_id_month_year_adset_name_key'), 'gold_campaign_insights', ['campaing_id', 'month', 'year', 'adset_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('gold_campaign_insights', 'ad_accounts_id')
    op.drop_column('gold_campaign_insights', 'campaign_id')
    # ### end Alembic commands ###
